# Generated by Django 5.0.7 on 2024-07-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='document',
            name='document_type_code_uq_1',
        ),
        migrations.AlterField(
            model_name='document',
            name='custom_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='document.custom_code'),
        ),
        migrations.AlterField(
            model_name='historicaldocument',
            name='custom_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='document.custom_code'),
        ),
    ]
