# Generated by Django 5.0.7 on 2024-09-21 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_remove_document_document_type_code_uq_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentstatuscourse',
            name='document',
            field=models.ForeignKey(db_column='id_document', on_delete=django.db.models.deletion.CASCADE, related_name='status_course', to='document.document'),
        ),
    ]
