# Generated by Django 5.1.3 on 2025-03-30 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_documenttypeaccountingtype_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttypeattributemapping',
            name='attribute',
            field=models.ForeignKey(db_column='id_document_type_attribute', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapping_set', to='document.documenttypeattribute'),
        ),
    ]
