# Generated by Django 5.0.7 on 2024-07-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogUserAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, null=True, verbose_name='user.action.log.username')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('action_type', models.CharField(max_length=20, verbose_name='user.action.log.action_type')),
                ('request_path', models.CharField(max_length=500, verbose_name='user.action.log.request_path')),
                ('url_name', models.CharField(max_length=200, verbose_name='user.action.log.url_name')),
                ('parameter_list', models.CharField(max_length=500, verbose_name='user.action.log.parameter_list')),
                ('date_created', models.DateTimeField(verbose_name='user.action.log.date_created')),
            ],
            options={
                'db_table': 'log_user_action',
            },
        ),
    ]
