# Generated by Django 5.0.7 on 2024-07-27 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TagCatergory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='tag.category.name')),
            ],
            options={
                'db_table': 'tag_category',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='tag.name')),
                ('category', models.ForeignKey(db_column='id_category', on_delete=django.db.models.deletion.CASCADE, to='tag.tagcatergory')),
            ],
            options={
                'db_table': 'tag',
            },
        ),
    ]
