# Generated by Django 5.0.7 on 2024-07-27 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeadPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Nazwa LP')),
            ],
            options={
                'verbose_name': 'strona',
                'verbose_name_plural': 'strony',
                'db_table': 'marketing_lp_lead_page',
            },
        ),
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nazwa medium')),
            ],
            options={
                'verbose_name': 'medium',
                'verbose_name_plural': 'medium',
                'db_table': 'marketing_lp_medium',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nazwa źródła')),
            ],
            options={
                'verbose_name': 'źródło',
                'verbose_name_plural': 'źródła',
                'db_table': 'marketing_lp_source',
            },
        ),
        migrations.CreateModel(
            name='PageEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data dodania')),
                ('first_name', models.CharField(blank=True, editable=False, max_length=254, null=True, verbose_name='Imię')),
                ('last_name', models.CharField(blank=True, editable=False, max_length=254, null=True, verbose_name='Nazwisko')),
                ('client_type', models.CharField(blank=True, editable=False, max_length=254, null=True, verbose_name='Podmiot')),
                ('company_name', models.CharField(blank=True, editable=False, max_length=254, null=True, verbose_name='Nazwa firmy')),
                ('phone', models.CharField(blank=True, editable=False, max_length=254, null=True, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, editable=False, max_length=254, null=True, verbose_name='Email')),
                ('epi', models.CharField(default='', max_length=255, null=True)),
                ('amount', models.BigIntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Kwota pożyczki / Wartość inna')),
                ('office_space', models.BigIntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Powierzchnia biura')),
                ('location', models.CharField(blank=True, editable=False, max_length=254, null=True, verbose_name='Lokalizacja biura')),
                ('message', models.TextField(blank=True, editable=False, null=True, verbose_name='Wiadomosc')),
                ('device', models.CharField(blank=True, editable=False, max_length=254, null=True, verbose_name='Device')),
                ('accept1', models.BooleanField(default=False, editable=False, verbose_name='Zgoda 1 (elektroniczna)')),
                ('accept2', models.BooleanField(default=False, editable=False, verbose_name='Zgoda 2 (telekomunikacyjna)')),
                ('accept3', models.BooleanField(default=False, editable=False, verbose_name='Zgoda 3')),
                ('accept4', models.BooleanField(default=False, editable=False, verbose_name='Zgoda 4')),
                ('accept5', models.BooleanField(default=False, editable=False, verbose_name='Zgoda 5')),
                ('lp', models.ForeignKey(db_column='id_lead_page', editable=False, on_delete=django.db.models.deletion.CASCADE, to='lp.leadpage')),
                ('medium', models.ForeignKey(blank=True, db_column='id_medium', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='lp.medium', verbose_name='Medium')),
                ('source', models.ForeignKey(blank=True, db_column='id_source', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='lp.source', verbose_name='Źródło')),
            ],
            options={
                'verbose_name': 'wpis',
                'verbose_name_plural': 'wpisy',
                'db_table': 'marketing_lp_page_entry',
            },
        ),
    ]
