# Generated by Django 5.0.7 on 2024-07-27 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attachment', '0001_initial'),
        ('document', '0002_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeContractType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('part_time', models.BooleanField(blank=True, default=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employee_contract_type',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='employee.hire_date')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='employee.completion_date')),
                ('init_holiday_days', models.IntegerField(default=0, verbose_name='employee.init_holiday_days')),
                ('curr_holiday_days', models.IntegerField(default=0, verbose_name='employee.curr_holiday_days')),
                ('prev_year_holiday_days', models.IntegerField(default=0, verbose_name='employee.prev_year_holiday_days')),
                ('curr_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='employee.curr_salary')),
                ('document_type', models.ForeignKey(db_column='id_document_type', on_delete=django.db.models.deletion.CASCADE, to='document.documenttype')),
            ],
            options={
                'db_table': 'user_employee',
            },
        ),
        migrations.CreateModel(
            name='EmployeeContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=300, null=True)),
                ('sign_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('part_time', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('contract_subject', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(db_column='id_employee', on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'db_table': 'employee_contract',
            },
        ),
        migrations.CreateModel(
            name='EmployeeContractAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sq', models.IntegerField()),
                ('id_attachment', models.ForeignKey(db_column='id_attachment', on_delete=django.db.models.deletion.CASCADE, to='attachment.attachment')),
                ('id_contract', models.ForeignKey(db_column='id_contract', on_delete=django.db.models.deletion.CASCADE, to='employee.employeecontract')),
            ],
            options={
                'db_table': 'employee_contract_attachment',
            },
        ),
        migrations.AddField(
            model_name='employeecontract',
            name='attachments',
            field=models.ManyToManyField(through='employee.EmployeeContractAttachment', to='attachment.attachment'),
        ),
        migrations.AddField(
            model_name='employeecontract',
            name='type',
            field=models.ForeignKey(db_column='id_type', on_delete=django.db.models.deletion.CASCADE, to='employee.employeecontracttype'),
        ),
    ]
