# Generated by Django 5.0.7 on 2024-07-27 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0002_initial'),
        ('document', '0002_initial'),
        ('meeting_room', '0001_initial'),
        ('schedule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalschedule',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='id_created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalschedule',
            name='custom_location_address',
            field=models.ForeignKey(blank=True, db_column='id_custom_loc_address', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='address.address'),
        ),
        migrations.AddField(
            model_name='historicalschedule',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalschedule',
            name='host_user',
            field=models.ForeignKey(blank=True, db_column='id_host_user', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='schedule.host_user'),
        ),
        migrations.AddField(
            model_name='historicalschedule',
            name='meeting_room',
            field=models.ForeignKey(blank=True, db_column='id_meeting_room', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='meeting_room.meetingroom', verbose_name='schedule.meeting_room'),
        ),
        migrations.AddField(
            model_name='historicalschedule',
            name='service',
            field=models.ForeignKey(blank=True, db_column='id_service', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='document.documenttype', verbose_name='schedule.service'),
        ),
        migrations.AddField(
            model_name='historicalschedule',
            name='superior_confirmed_by',
            field=models.ForeignKey(blank=True, db_column='id_superior_confirmed_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalschedulecyclical',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='id_created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalschedulecyclical',
            name='custom_location_address',
            field=models.ForeignKey(blank=True, db_column='id_custom_loc_address', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='address.address'),
        ),
        migrations.AddField(
            model_name='historicalschedulecyclical',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalschedulecyclical',
            name='host_user',
            field=models.ForeignKey(blank=True, db_column='id_host_user', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='schedule.cyclical.host_user'),
        ),
        migrations.AddField(
            model_name='historicalschedulecyclical',
            name='meeting_room',
            field=models.ForeignKey(blank=True, db_column='id_meeting_room', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='meeting_room.meetingroom', verbose_name='schedule.cyclical.meeting_room'),
        ),
        migrations.AddField(
            model_name='historicalschedulecyclicaluser',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalschedulecyclicaluser',
            name='user',
            field=models.ForeignKey(blank=True, db_column='id_user', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalscheduleuser',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalscheduleuser',
            name='user',
            field=models.ForeignKey(blank=True, db_column='id_user', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schedule',
            name='created_by',
            field=models.ForeignKey(db_column='id_created_by', on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schedule',
            name='custom_location_address',
            field=models.ForeignKey(blank=True, db_column='id_custom_loc_address', null=True, on_delete=django.db.models.deletion.CASCADE, to='address.address'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='host_user',
            field=models.ForeignKey(db_column='id_host_user', on_delete=django.db.models.deletion.CASCADE, related_name='host_user', to=settings.AUTH_USER_MODEL, verbose_name='schedule.host_user'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='meeting_room',
            field=models.ForeignKey(blank=True, db_column='id_meeting_room', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_room', to='meeting_room.meetingroom', verbose_name='schedule.meeting_room'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='service',
            field=models.ForeignKey(blank=True, db_column='id_service', null=True, on_delete=django.db.models.deletion.CASCADE, to='document.documenttype', verbose_name='schedule.service'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='superior_confirmed_by',
            field=models.ForeignKey(blank=True, db_column='id_superior_confirmed_by', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalscheduleuser',
            name='schedule',
            field=models.ForeignKey(blank=True, db_column='id_schedule', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='schedule.schedule'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='calendar',
            field=models.ForeignKey(db_column='id_calendar', null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.schedulecalendar'),
        ),
        migrations.AddField(
            model_name='historicalschedule',
            name='calendar',
            field=models.ForeignKey(blank=True, db_column='id_calendar', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='schedule.schedulecalendar'),
        ),
        migrations.AddField(
            model_name='schedulecalendarscheduletypem2m',
            name='calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.schedulecalendar'),
        ),
        migrations.AddField(
            model_name='schedulecyclical',
            name='created_by',
            field=models.ForeignKey(db_column='id_created_by', on_delete=django.db.models.deletion.CASCADE, related_name='cyclical_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schedulecyclical',
            name='custom_location_address',
            field=models.ForeignKey(blank=True, db_column='id_custom_loc_address', null=True, on_delete=django.db.models.deletion.CASCADE, to='address.address'),
        ),
        migrations.AddField(
            model_name='schedulecyclical',
            name='host_user',
            field=models.ForeignKey(db_column='id_host_user', on_delete=django.db.models.deletion.CASCADE, related_name='cyclical_host_user', to=settings.AUTH_USER_MODEL, verbose_name='schedule.cyclical.host_user'),
        ),
        migrations.AddField(
            model_name='schedulecyclical',
            name='meeting_room',
            field=models.ForeignKey(blank=True, db_column='id_meeting_room', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cyclical_meeting_room', to='meeting_room.meetingroom', verbose_name='schedule.cyclical.meeting_room'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='cyclical',
            field=models.ForeignKey(blank=True, db_column='id_cyclical', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cyclical', to='schedule.schedulecyclical'),
        ),
        migrations.AddField(
            model_name='historicalschedulecyclicaluser',
            name='schedule',
            field=models.ForeignKey(blank=True, db_column='id_schedule', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='schedule.schedulecyclical'),
        ),
        migrations.AddField(
            model_name='historicalschedule',
            name='cyclical',
            field=models.ForeignKey(blank=True, db_column='id_cyclical', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='schedule.schedulecyclical'),
        ),
        migrations.AddField(
            model_name='schedulecyclicalexclude',
            name='cyclical',
            field=models.ForeignKey(db_column='id_cyclical', on_delete=django.db.models.deletion.CASCADE, to='schedule.schedulecyclical'),
        ),
        migrations.AddField(
            model_name='schedulecyclicaluser',
            name='schedule',
            field=models.ForeignKey(db_column='id_schedule', on_delete=django.db.models.deletion.CASCADE, related_name='cyclical_membership', to='schedule.schedulecyclical'),
        ),
        migrations.AddField(
            model_name='schedulecyclicaluser',
            name='user',
            field=models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, related_name='cyclical_user_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schedulecyclical',
            name='invited_users',
            field=models.ManyToManyField(blank=True, related_name='cyclical_invited', through='schedule.ScheduleCyclicalUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schedulenote',
            name='schedule',
            field=models.ForeignKey(db_column='id_schedule', on_delete=django.db.models.deletion.CASCADE, related_name='message_set', to='schedule.schedule'),
        ),
        migrations.AddField(
            model_name='schedulenote',
            name='user',
            field=models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schedulecyclical',
            name='type',
            field=models.ForeignKey(db_column='id_type', on_delete=django.db.models.deletion.CASCADE, to='schedule.scheduletype'),
        ),
        migrations.AddField(
            model_name='schedulecalendarscheduletypem2m',
            name='schedule_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.scheduletype'),
        ),
        migrations.AddField(
            model_name='schedulecalendar',
            name='allowed_event_types',
            field=models.ManyToManyField(through='schedule.ScheduleCalendarScheduleTypeM2M', to='schedule.scheduletype'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='type',
            field=models.ForeignKey(db_column='id_type', on_delete=django.db.models.deletion.CASCADE, to='schedule.scheduletype'),
        ),
        migrations.AddField(
            model_name='historicalschedulecyclical',
            name='type',
            field=models.ForeignKey(blank=True, db_column='id_type', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='schedule.scheduletype'),
        ),
        migrations.AddField(
            model_name='historicalschedule',
            name='type',
            field=models.ForeignKey(blank=True, db_column='id_type', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='schedule.scheduletype'),
        ),
        migrations.AddField(
            model_name='scheduleuser',
            name='schedule',
            field=models.ForeignKey(db_column='id_schedule', on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='schedule.schedule'),
        ),
        migrations.AddField(
            model_name='scheduleuser',
            name='user',
            field=models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, related_name='schedule_user_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schedule',
            name='invited_users',
            field=models.ManyToManyField(blank=True, related_name='invited', through='schedule.ScheduleUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='schedulecyclicaluser',
            unique_together={('schedule', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='schedulecalendarscheduletypem2m',
            unique_together={('calendar', 'schedule_type')},
        ),
        migrations.AlterUniqueTogether(
            name='scheduleuser',
            unique_together={('schedule', 'user')},
        ),
    ]
