# Generated by Django 5.0.7 on 2024-07-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('code', models.CharField(max_length=200, null=True)),
                ('xml_data', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=10)),
                ('file_path', models.CharField(max_length=500)),
                ('file_name', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'report',
            },
        ),
        migrations.CreateModel(
            name='ReportDatasourceDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type_id', models.IntegerField(verbose_name='report.data.definition.document_type_id')),
                ('document_attribute_id', models.IntegerField(blank=True, null=True, verbose_name='report.data.definition.document_attribute_id')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='report.data.definition.name')),
                ('tag_name', models.CharField(max_length=200, verbose_name='report.data.definition.tag_name')),
                ('detail_section_id', models.IntegerField(blank=True, null=True, verbose_name='report.data.definition.document_type_id')),
                ('getter_function', models.CharField(blank=True, max_length=200, null=True, verbose_name='report.data.definition.getter_function')),
                ('mapping_column', models.CharField(blank=True, max_length=200, null=True, verbose_name='report.data.definition.mapping_column')),
                ('format', models.CharField(blank=True, max_length=200, null=True, verbose_name='report.data.definition.format')),
                ('type', models.CharField(blank=True, max_length=200, null=True, verbose_name='report.data.definition.type')),
                ('editable', models.BooleanField(default=False, verbose_name='report.data.definition.editable')),
                ('required', models.BooleanField(default=False, verbose_name='report.data.definition.editable')),
                ('sq', models.IntegerField()),
            ],
            options={
                'db_table': 'report_datasource_definition',
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_template', models.TextField(blank=True, null=True, verbose_name='report.template.html_template')),
                ('name', models.CharField(max_length=200, verbose_name='report.template.name')),
                ('code', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('JASPER', 'jasper'), ('XLS', 'Excel template'), ('DOC', 'Word template'), ('HTML', 'Html template')], max_length=200, verbose_name='report.template.type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='report.template.description')),
                ('file_name', models.CharField(blank=True, db_index=True, max_length=200, null=True, unique=True, verbose_name='report.template.file_name')),
                ('source_type', models.CharField(default='STATIC', max_length=10, verbose_name='report.template.source_type')),
                ('query', models.TextField(blank=True, null=True, verbose_name='report.template.source_type')),
                ('query_json', models.JSONField(default=dict)),
                ('params_mapping', models.JSONField(default=dict)),
                ('root_dir', models.CharField(blank=True, max_length=500, null=True, verbose_name='report.template.root_dir')),
                ('features', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'report_template',
            },
        ),
    ]
