# Generated by Django 5.0.7 on 2024-07-27 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('report', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='created_by',
            field=models.ForeignKey(db_column='id_created_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportdatasourcedefinition',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='id_parent', null=True, on_delete=django.db.models.deletion.CASCADE, to='report.reportdatasourcedefinition'),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='footer_template_include',
            field=models.ForeignKey(blank=True, db_column='id_footer_template_include', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='footer_template_include_set', to='report.reporttemplate'),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='header_template_include',
            field=models.ForeignKey(blank=True, db_column='id_header_template_include', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='header_template_include_set', to='report.reporttemplate'),
        ),
        migrations.AddField(
            model_name='reportdatasourcedefinition',
            name='report',
            field=models.ForeignKey(db_column='id_report', on_delete=django.db.models.deletion.CASCADE, related_name='datasource_definition_set', to='report.reporttemplate'),
        ),
        migrations.AddField(
            model_name='report',
            name='template',
            field=models.ForeignKey(db_column='id_template', on_delete=django.db.models.deletion.CASCADE, to='report.reporttemplate'),
        ),
    ]
