from django.conf import settings

PRE_ANNEX_STATUS = 'PRE_ANX'
ANNEX_STATUS = 'ANX'
FORCE_CALCULATION = True

CONSTANT_DAYS_IN_YEAR = True

INTEREST_NOMINAL = 'NOMINAL'
INTEREST_FOR_DELAY = 'FOR_DELAY'
INTEREST_FOR_DELAY_MAX = 'FOR_DELAY_MAX'