# Generated by Django 5.0.7 on 2024-07-27 12:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        ('hierarchy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRoomAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
                ('code', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'meeting_room_attribute',
            },
        ),
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_local', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('seats', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_seats', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('av_hour_from', models.TimeField(blank=True, null=True)),
                ('av_hour_to', models.TimeField(blank=True, null=True)),
                ('max_continous_events', models.PositiveIntegerField(blank=True, null=True, verbose_name='meeting_room.max_continous_events')),
                ('min_break', models.PositiveIntegerField(blank=True, null=True, verbose_name='meeting_room.min_break')),
                ('color', models.CharField(blank=True, max_length=7, null=True, verbose_name='meeting_room.color')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.address')),
                ('headquarter', models.ForeignKey(blank=True, db_column='id_headquarter', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hierarchy.hierarchy', verbose_name='meeting_room.hierarchy')),
            ],
            options={
                'db_table': 'meeting_room',
            },
        ),
        migrations.CreateModel(
            name='MeetingRoomRoomAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_room', models.ForeignKey(db_column='id_room', on_delete=django.db.models.deletion.CASCADE, to='meeting_room.meetingroom')),
                ('meeting_room_attribute', models.ForeignKey(db_column='id_attribute', on_delete=django.db.models.deletion.CASCADE, to='meeting_room.meetingroomattribute')),
            ],
            options={
                'db_table': 'meeting_room_room_attribute',
            },
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='attributes',
            field=models.ManyToManyField(blank=True, through='meeting_room.MeetingRoomRoomAttribute', to='meeting_room.meetingroomattribute'),
        ),
    ]
