XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX

        XXXX XXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXX

        BB BBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX

            XXXXXX
        BBBBB
                XXXX XXXXXXXXXXXXXXXXXX

                BBB B BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

                    BB BBBBBBBBBBBBBBB B BBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBB B BBBBBBBBBBBBBBBBB
                    BBBB BBBBBBBBBBBBBBB BB BBBBBBBBBBB
                        XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                    BBBB
                        XX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXX XXXXXXXXXXXXX
                    BBBBB
                BBBBBB
                XXXXXX


                BB BBBBBBBBBBBBB
                    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX

                    XX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX
                    XXXXXX
                BBBBB
    XXXXXXX
        XXXXXX
    XXXXXX
XXXXXX