XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX

            XXXX XXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXX
        BB BBBBBBBBBBBBBBBBB
            XX XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        BBBBB
                BBB B BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                    BB BBBBBBBBBBBBBBB BB BBBBBBBBBBB
                        XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                    BBBB
                        XX XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX
                    BBBBB
                BBBBBB

                BB BBBBBBBBBBBBB
                    XX XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                BBBBB
    XXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX