XXX XXXXXXXXXXXXXXXXXXX
    BB BBBBBBBBBBBBBBBBBBBBB
        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    BBBB
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    BBBBB
    BBB B BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        BB BBBBBBBBBBBBBBB BB B
            XXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        BBBB
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        BBBBB
    BBBBBB
    BB BBBBBBBBBBBBBBBBB
        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    BBBB
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    BBBBB
XXXXX