# Generated by Django 5.0.7 on 2024-07-27 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batch_processing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_from', models.CharField(max_length=28, verbose_name='transaction.account_from')),
                ('account_to', models.CharField(max_length=28, verbose_name='transaction.account_to')),
                ('account_name_from', models.CharField(blank=True, max_length=500, null=True, verbose_name='transaction.account_name_from')),
                ('account_name_to', models.CharField(blank=True, max_length=500, null=True, verbose_name='transaction.account_name_to')),
                ('v_account_iph', models.CharField(blank=True, max_length=28, null=True, verbose_name='transaction.v_account_iph')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='transaction.title')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='transaction.value')),
                ('transaction_no', models.CharField(max_length=50, verbose_name='transaction.transaction_number')),
                ('transaction_date', models.DateField(verbose_name='transaction.transaction_date')),
                ('accounting_date', models.DateField(verbose_name='transaction.accounting_date')),
                ('source_name', models.CharField(max_length=50, verbose_name='transaction.source_name')),
                ('source_type', models.CharField(max_length=20, verbose_name='transaction.source_type')),
                ('source_filename', models.CharField(blank=True, max_length=300, null=True, verbose_name='transaction.source_filename')),
                ('source_file_type', models.CharField(max_length=50, verbose_name='transaction.source_filetype')),
                ('destination_id', models.IntegerField(blank=True, null=True)),
                ('file', models.ForeignKey(blank=True, db_column='id_file', null=True, on_delete=django.db.models.deletion.CASCADE, to='batch_processing.file')),
            ],
            options={
                'db_table': 'fa_transaction',
            },
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('transaction_no', 'source_name'), name='unique_trn_no_source_name'),
        ),
    ]
