# Generated by Django 5.0.7 on 2024-07-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('header', models.CharField(blank=True, max_length=200, null=True, verbose_name='note.header')),
                ('text', models.TextField(verbose_name='note.text')),
                ('importance', models.CharField(choices=[('high_priority', 'HIGH'), ('normal_priority', 'NORMAL'), ('low_priority', 'LOW')], default='NORMAL', max_length=50)),
            ],
            options={
                'db_table': 'note',
            },
        ),
    ]
