XXXXXXXXXX
XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXX XXX XXXXXXX XXXXXXXXX XXX XXXX XXX XXXXXX
XX XXXXXXXXXXX XXXXXXXXXXXXX XX XXXXX XXXXXXXXXXXXXX
    XX XXXXXXXXXXX X XXXXXXXXXXX XXXXXXXXX
    XX XXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXX X XXXXXXXXXXXXX XXXXXXXXX

XXX
XX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X XXXXXX
XX XXXXXXXX XXX XXXXX XXXXX XXXXXXXXXX XX XXXXX XXXX XXXX X XXXXXXX XXXXXXX XXXX XXX XXXXX X XXXXX X XXXXX X XXXXXXXX
   XXX XXXX XX XXXX XXXXXX XXXX XXX XXXXXXX XXXX XXXXXXXXXXXX XX XXXXXXXXX XXXXX XXXXXXX XXXXX XXXX X XXXXXX XXXXXXX

XXXXXX
XX XXXXXXXXXXXX XXXXXX
    XX XXXXXXXXXXXXX X XXXXXXXXXXX XXXXX
        XX XXXXX XXX XXXXXX
        XX XXXXXXXXXX XXXXXX XXX XXXXXXXXX XXXXXX X XXXXXXXXXXXX XXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

X XXXXXX XXXXXXXXXXXX

X XXXXXXXX XXXXXXXXX
  X XXXXX XXX X XXXXXXXXXX XXX XXXXXXX XXXXX XXXXXX XXXXXX