# Generated by Django 5.0.7 on 2024-07-27 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('message', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmessagetemplate',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagequeue',
            name='template',
            field=models.ForeignKey(db_column='id_template', on_delete=django.db.models.deletion.CASCADE, to='message.messagetemplate'),
        ),
        migrations.AddField(
            model_name='messagetemplateparam',
            name='template',
            field=models.ForeignKey(db_column='id_template', on_delete=django.db.models.deletion.CASCADE, related_name='params', to='message.messagetemplate'),
        ),
    ]
