XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    
    XXXX XXXXXXXBB BBB BBBBBBBBBBBBXXXXXXXXXXX XXXXXXXXXXXXXXBBBBXXXXXXXXXXBBBBBXX

        BB BBB BBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXXX
            XXXXXX
        BBBBB

        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX
               XXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXXX
    
    XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXX XXXXXXXFFFFFFFFFFFFFFFFFFXXX
XXXXXX
