XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    
    XXXX XXXXXXXBB BBB BBBBBBBBBBBBXXXXXXXXXXX XXXXXXXXXXXXXXBBBBXXXXXXXXXXBBBBBXX

        BB BBB BBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXX
                    BBB BBBBBBBBBB BBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBB
                        BB BBBBBBBBB
                            XXXX
                                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXXX XXXXXXXXX
                                        XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                                               XXXXXXXXXXX
                                               XXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXBBBBBX
                                        XXXXXXXX
                                XXXXXX
                            XXXXX
                        BBBBB
                    BBBBBB
                XXXXX
            XXXXXX
        BBBBB

        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX
               XXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXBBBBBXX
    XXXXXX
    
    XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXX XXXXXXXFFFFFFFFFFFFFFFFFFXXX
XXXXXX