
BB BBBBB
    BB BBB BBBB
        XXXX XXXXXXXXXXXXXXXXXBB BBBBBBBBBBBB XXXXXXXXXXXXXXXXBBBBBXX
    BBBBB
BB BBBBBBBBBBBBBBBBBBBBB BB BBBBBBB
    BB BBBBBBBBBBBBBBBBB
        BB BBB BBBBBBBBB
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBB
        BBBB
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBB
        BBBBB
    BBBB
        BB BBB BBBBBBBBB
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBB
        BBBB
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBB
        BBBBB
    BBBBB
BBBB

    

    BB BBB BBBBBBB
        BB BBBBBBBBBBBBBBBBBBBB
            
        BBBB
            XXXXXX XXXXXXXBBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBX
                   XXXXXXXXXXXXXXX
        BBBBB
    BBBBB

    

BBBBB
BB BBB BBBB
    XXXXXX
BBBBB
BBBBB





