# Generated by Django 5.0.7 on 2024-07-27 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adviser', '0001_initial'),
        ('broker', '0001_initial'),
        ('client', '0001_initial'),
        ('document', '0002_initial'),
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerlead',
            name='adviser',
            field=models.ForeignKey(blank=True, db_column='id_adviser', null=True, on_delete=django.db.models.deletion.CASCADE, to='adviser.adviser'),
        ),
        migrations.AddField(
            model_name='partnerlead',
            name='broker',
            field=models.ForeignKey(blank=True, db_column='id_broker', null=True, on_delete=django.db.models.deletion.CASCADE, to='broker.broker'),
        ),
        migrations.AddField(
            model_name='partnerlead',
            name='client',
            field=models.ForeignKey(blank=True, db_column='id_client', null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
        migrations.AddField(
            model_name='partnerlead',
            name='document',
            field=models.ForeignKey(blank=True, db_column='id_document', null=True, on_delete=django.db.models.deletion.CASCADE, to='document.document'),
        ),
        migrations.AddField(
            model_name='partnerleadagreement',
            name='agreement',
            field=models.ForeignKey(db_column='id_agreement', on_delete=django.db.models.deletion.CASCADE, to='partner.partneragreement'),
        ),
        migrations.AddField(
            model_name='partnerleadagreement',
            name='lead',
            field=models.ForeignKey(db_column='id_lead', on_delete=django.db.models.deletion.CASCADE, related_name='agreement_set', to='partner.partnerlead'),
        ),
        migrations.AddField(
            model_name='partnerlead',
            name='agreements',
            field=models.ManyToManyField(blank=True, through='partner.PartnerLeadAgreement', to='partner.partneragreement', verbose_name='parnter.lead.agreements'),
        ),
        migrations.AddField(
            model_name='partnerlead',
            name='security_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='partner.partnersecuritytype', verbose_name='parnter.lead.security_type'),
        ),
    ]
