# Generated by Django 5.0.7 on 2024-07-27 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dict', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeObjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('attribute_class', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'attribute_object_type',
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='attribute.name.label')),
                ('description', models.TextField(blank=True, null=True, verbose_name='attribute.description.label')),
                ('regex', models.CharField(blank=True, max_length=300, null=True, verbose_name='attribute.regex.label')),
                ('mask', models.CharField(blank=True, max_length=200, null=True, verbose_name='attribute.mask')),
                ('default_format', models.CharField(blank=True, max_length=100, null=True, verbose_name='attribute.default_format.label')),
                ('generic_datatype', models.CharField(max_length=100, verbose_name='attribute.generic_datatype.label')),
                ('subtype', models.CharField(blank=True, max_length=100, null=True, verbose_name='attribute.subtype')),
                ('min_length', models.IntegerField(blank=True, null=True, verbose_name='attribute.min_length.label')),
                ('max_length', models.IntegerField(blank=True, null=True, verbose_name='attribute.max_length.label')),
                ('min_value', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='attribute.min_value.label')),
                ('max_value', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='attribute.max_value.label')),
                ('decimal_places', models.IntegerField(blank=True, null=True, verbose_name='attribute.decimal_places.label')),
                ('no_data', models.BooleanField(default=False)),
                ('dictionary', models.ForeignKey(blank=True, db_column='id_dictionary', null=True, on_delete=django.db.models.deletion.CASCADE, to='dict.dictionary', verbose_name='attribute.dictionary.label')),
            ],
            options={
                'db_table': 'attribute',
            },
        ),
        migrations.CreateModel(
            name='AttributeFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='attribute.validator.name.label')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='attribute.validator.code.label')),
                ('description', models.TextField(blank=True, null=True, verbose_name='attribute.validator.description.label')),
                ('attribute', models.ForeignKey(db_column='id_attribute', on_delete=django.db.models.deletion.CASCADE, to='attribute.attribute')),
            ],
            options={
                'db_table': 'attribute_format',
            },
        ),
        migrations.CreateModel(
            name='AttributeSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('sq', models.IntegerField(default=0)),
                ('object_type', models.ForeignKey(db_column='id_object_type', on_delete=django.db.models.deletion.CASCADE, related_name='section_object_type', to='attribute.attributeobjecttype')),
            ],
            options={
                'db_table': 'attribute_section',
            },
        ),
        migrations.CreateModel(
            name='AttributeValidator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('regex', models.CharField(blank=True, max_length=300, null=True)),
                ('validator_class', models.CharField(blank=True, max_length=200, null=True)),
                ('error_message', models.TextField(default='')),
                ('sq', models.IntegerField(default=0)),
                ('attribute_datatype', models.ForeignKey(db_column='id_attribute_datatype', on_delete=django.db.models.deletion.CASCADE, to='attribute.attribute')),
            ],
            options={
                'db_table': 'attribute_validator',
            },
        ),
        migrations.CreateModel(
            name='AttributeObjectTypeAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('sq', models.IntegerField(default=0)),
                ('data_type', models.ForeignKey(db_column='id_data_type', on_delete=django.db.models.deletion.CASCADE, related_name='data_type', to='attribute.attribute')),
                ('object_type', models.ForeignKey(db_column='id_object_type', on_delete=django.db.models.deletion.CASCADE, related_name='attribute_object_type', to='attribute.attributeobjecttype')),
                ('section', models.ForeignKey(db_column='id_section', on_delete=django.db.models.deletion.CASCADE, related_name='section', to='attribute.attributesection')),
            ],
            options={
                'db_table': 'attribute_object_type_attribute',
                'unique_together': {('code', 'object_type', 'object_id')},
            },
        ),
    ]
