# Generated by Django 5.0.7 on 2024-07-27 12:46

import application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='company.name')),
                ('establish_date', models.DateField(blank=True, null=True, verbose_name='company.establish_date')),
                ('legal_form', models.CharField(blank=True, max_length=200, null=True, verbose_name='company.legal_form')),
                ('description', models.TextField(blank=True, null=True, verbose_name='company.description')),
                ('activity_status', models.CharField(blank=True, choices=[('ACT', 'aktywna'), ('INACT', 'nieaktywna')], max_length=50, null=True, verbose_name='company.activity_status')),
            ],
            options={
                'db_table': 'company',
            },
            bases=(application.models.AddressMixin, application.models.CompanyDataMixin, application.models.ContactDataMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CompanyManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('role', models.CharField(choices=[('chairman of the board', 'COB'), ('member of the board', 'MOB'), ('proxy', 'PRX')], max_length=100, verbose_name='company_management.role')),
                ('description', models.TextField(blank=True, null=True, verbose_name='company_management.description')),
            ],
            options={
                'db_table': 'company_management',
            },
        ),
    ]
