# Generated by Django 5.2.7 on 2025-10-05 13:25

import application.models
import py3ws.utils.validators
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.JSONField(default=dict, validators=[application.models.AddressMixin.json_address_validator]),
        ),
        migrations.AddField(
            model_name='company',
            name='krs',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[utils.validators.krs_validator], verbose_name='krs'),
        ),
        migrations.AddField(
            model_name='company',
            name='nip',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[utils.validators.nip_validator], verbose_name='nip'),
        ),
        migrations.AddField(
            model_name='company',
            name='regon',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[py3ws.utils.validators.regon_validator], verbose_name='regon'),
        ),
    ]
