# Generated by Django 5.0.7 on 2024-07-27 12:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('text', models.TextField()),
                ('params', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notification_template',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('type', models.CharField(default='INFO', max_length=20)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('effective_date', models.DateField(default=django.utils.timezone.now)),
                ('template', models.ForeignKey(blank=True, db_column='id_template', null=True, on_delete=django.db.models.deletion.CASCADE, to='notification.notificationtemplate')),
            ],
            options={
                'db_table': 'notification',
                'ordering': ('-effective_date',),
            },
        ),
        migrations.CreateModel(
            name='NotificationUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
                ('priority', models.CharField(default='STD', max_length=10)),
                ('close_date', models.DateTimeField(blank=True, null=True)),
                ('notification', models.ForeignKey(db_column='id_notification', on_delete=django.db.models.deletion.CASCADE, to='notification.notification')),
            ],
            options={
                'db_table': 'notification_user',
                'ordering': ('-notification__creation_date', '-notification__pk'),
            },
        ),
    ]
