# Generated by Django 5.0.7 on 2024-07-27 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationuser',
            name='user',
            field=models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, related_name='notification_user_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='users',
            field=models.ManyToManyField(through='notification.NotificationUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
