# Generated by Django 5.0.7 on 2024-07-27 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adviser', '0001_initial'),
        ('attachment', '0001_initial'),
        ('broker', '0001_initial'),
        ('client', '0001_initial'),
        ('document', '0002_initial'),
        ('hierarchy', '0001_initial'),
        ('product', '0001_initial'),
        ('report', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproductinterest',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='adviser',
            field=models.ForeignKey(blank=True, db_column='id_adviser', null=True, on_delete=django.db.models.deletion.CASCADE, to='adviser.adviser'),
        ),
        migrations.AddField(
            model_name='product',
            name='broker',
            field=models.ForeignKey(blank=True, db_column='id_broker', null=True, on_delete=django.db.models.deletion.CASCADE, to='broker.broker'),
        ),
        migrations.AddField(
            model_name='product',
            name='client',
            field=models.ForeignKey(db_column='id_client', on_delete=django.db.models.deletion.CASCADE, related_name='product_set', to='client.client'),
        ),
        migrations.AddField(
            model_name='product',
            name='creation_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creation_user', to=settings.AUTH_USER_MODEL, verbose_name='product.creation_user'),
        ),
        migrations.AddField(
            model_name='product',
            name='creditor',
            field=models.ForeignKey(blank=True, db_column='id_creditor', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creditor', to='hierarchy.hierarchy'),
        ),
        migrations.AddField(
            model_name='product',
            name='document',
            field=models.OneToOneField(blank=True, db_column='id_document', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='document.document'),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.ForeignKey(db_column='id_type', on_delete=django.db.models.deletion.CASCADE, to='document.documenttype'),
        ),
        migrations.AddField(
            model_name='historicalproductinterest',
            name='product',
            field=models.ForeignKey(blank=True, db_column='id_product', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.product'),
        ),
        migrations.AddField(
            model_name='productaccounting',
            name='accounting_type',
            field=models.ForeignKey(db_column='id_accounting_type', on_delete=django.db.models.deletion.CASCADE, to='document.documenttypeaccountingtype'),
        ),
        migrations.AddField(
            model_name='productaccounting',
            name='product',
            field=models.ForeignKey(db_column='id_product', on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='accounting',
            field=models.ManyToManyField(through='product.ProductAccounting', to='document.documenttypeaccountingtype'),
        ),
        migrations.AddField(
            model_name='productaction',
            name='created_by',
            field=models.ForeignKey(db_column='id_created_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productaction',
            name='product',
            field=models.ForeignKey(db_column='id_product', on_delete=django.db.models.deletion.CASCADE, related_name='action_set', to='product.product'),
        ),
        migrations.AddField(
            model_name='productaction',
            name='report',
            field=models.ForeignKey(blank=True, db_column='id_report', null=True, on_delete=django.db.models.deletion.CASCADE, to='report.report'),
        ),
        migrations.AddField(
            model_name='productactionattachment',
            name='attachment',
            field=models.ForeignKey(db_column='id_attachment', on_delete=django.db.models.deletion.CASCADE, to='attachment.attachment'),
        ),
        migrations.AddField(
            model_name='productactionattachment',
            name='product',
            field=models.ForeignKey(db_column='id_product', on_delete=django.db.models.deletion.CASCADE, to='product.productaction'),
        ),
        migrations.AddField(
            model_name='productaction',
            name='attachments',
            field=models.ManyToManyField(through='product.ProductActionAttachment', to='attachment.attachment'),
        ),
        migrations.AddField(
            model_name='productactiondefinition',
            name='document_type',
            field=models.ForeignKey(blank=True, db_column='id_document_type', null=True, on_delete=django.db.models.deletion.CASCADE, to='document.documenttype'),
        ),
        migrations.AddField(
            model_name='productactiondefinition',
            name='report',
            field=models.ForeignKey(blank=True, db_column='id_report', null=True, on_delete=django.db.models.deletion.CASCADE, to='report.reporttemplate'),
        ),
        migrations.AddField(
            model_name='productaction',
            name='action',
            field=models.ForeignKey(blank=True, db_column='id_action', null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productactiondefinition'),
        ),
        migrations.AddField(
            model_name='productattachment',
            name='attachment',
            field=models.ForeignKey(db_column='id_attachment', on_delete=django.db.models.deletion.CASCADE, to='attachment.attachment'),
        ),
        migrations.AddField(
            model_name='productattachment',
            name='attachment_owner',
            field=models.ForeignKey(db_column='id_product', on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='attachments',
            field=models.ManyToManyField(through='product.ProductAttachment', to='attachment.attachment'),
        ),
        migrations.AddField(
            model_name='productcalculation',
            name='product',
            field=models.ForeignKey(db_column='id_product', on_delete=django.db.models.deletion.CASCADE, related_name='calculation', to='product.product'),
        ),
        migrations.AddField(
            model_name='productcashflow',
            name='product',
            field=models.ForeignKey(db_column='id_product', on_delete=django.db.models.deletion.CASCADE, related_name='cashflow_set', to='product.product'),
        ),
        migrations.AddField(
            model_name='productcashflow',
            name='type',
            field=models.ForeignKey(db_column='id_type', on_delete=django.db.models.deletion.CASCADE, to='document.documenttypeaccountingtype'),
        ),
        migrations.AddField(
            model_name='productclient',
            name='client',
            field=models.ForeignKey(db_column='id_client', on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
        migrations.AddField(
            model_name='productclient',
            name='function',
            field=models.ForeignKey(db_column='id_function', on_delete=django.db.models.deletion.CASCADE, to='client.clientfunction', verbose_name='product.client.function'),
        ),
        migrations.AddField(
            model_name='productclient',
            name='product',
            field=models.ForeignKey(db_column='id_product', on_delete=django.db.models.deletion.CASCADE, related_name='client_set', to='product.product'),
        ),
        migrations.AddField(
            model_name='productcommission',
            name='product',
            field=models.ForeignKey(db_column='id_product', on_delete=django.db.models.deletion.CASCADE, related_name='commission_set', to='product.product'),
        ),
        migrations.AddField(
            model_name='productinterest',
            name='product',
            field=models.ForeignKey(db_column='id_product', on_delete=django.db.models.deletion.CASCADE, related_name='interest_set', to='product.product'),
        ),
        migrations.AddField(
            model_name='productinterestglobal',
            name='created_by',
            field=models.ForeignKey(db_column='id_created_by', on_delete=django.db.models.deletion.CASCADE, related_name='interest_global_created_by', to=settings.AUTH_USER_MODEL, verbose_name='product.interest.global.created_by'),
        ),
        migrations.AddField(
            model_name='productinterestglobal',
            name='document_type',
            field=models.ForeignKey(db_column='id_document_type', on_delete=django.db.models.deletion.CASCADE, to='document.documenttype', verbose_name='product.interest.global.document_type'),
        ),
        migrations.AddField(
            model_name='productinterest',
            name='type',
            field=models.ForeignKey(db_column='id_type', on_delete=django.db.models.deletion.CASCADE, related_name='type', to='product.productinteresttype', verbose_name='product.interest.type'),
        ),
        migrations.AddField(
            model_name='historicalproductinterest',
            name='type',
            field=models.ForeignKey(blank=True, db_column='id_type', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.productinteresttype', verbose_name='product.interest.type'),
        ),
        migrations.AddField(
            model_name='productschedule',
            name='product',
            field=models.ForeignKey(db_column='id_product', on_delete=django.db.models.deletion.CASCADE, related_name='schedule_set', to='product.product'),
        ),
        migrations.AddField(
            model_name='productstatustrack',
            name='created_by',
            field=models.ForeignKey(db_column='id_created_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productstatustrack',
            name='product',
            field=models.ForeignKey(db_column='id_product', on_delete=django.db.models.deletion.CASCADE, related_name='status_track_set', to='product.product'),
        ),
        migrations.AddField(
            model_name='producttypeaction',
            name='action',
            field=models.ForeignKey(db_column='id_action', on_delete=django.db.models.deletion.CASCADE, to='product.productactiondefinition'),
        ),
        migrations.AddField(
            model_name='producttypeaction',
            name='product',
            field=models.ForeignKey(db_column='id_product', on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='producttypecommission',
            name='document_type',
            field=models.ForeignKey(db_column='id_document_type', on_delete=django.db.models.deletion.CASCADE, related_name='commission_set', to='document.documenttype'),
        ),
        migrations.AddField(
            model_name='productcommission',
            name='commission',
            field=models.ForeignKey(db_column='id_commission', on_delete=django.db.models.deletion.CASCADE, related_name='product_set', to='product.producttypecommission'),
        ),
        migrations.AddField(
            model_name='producttypestatus',
            name='type',
            field=models.ForeignKey(db_column='id_type', on_delete=django.db.models.deletion.CASCADE, related_name='product_status_set', to='document.documenttype'),
        ),
        migrations.AddField(
            model_name='producttypeprocessflow',
            name='available_status',
            field=models.ForeignKey(blank=True, db_column='id_available_status', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='available_status', to='product.producttypestatus'),
        ),
        migrations.AddField(
            model_name='producttypeprocessflow',
            name='status',
            field=models.ForeignKey(db_column='id_current_status', on_delete=django.db.models.deletion.CASCADE, related_name='status', to='product.producttypestatus'),
        ),
        migrations.AddField(
            model_name='productstatustrack',
            name='status',
            field=models.ForeignKey(db_column='id_status', on_delete=django.db.models.deletion.CASCADE, to='product.producttypestatus'),
        ),
        migrations.AddField(
            model_name='productcalculation',
            name='product_status',
            field=models.ForeignKey(db_column='id_product_type_status', on_delete=django.db.models.deletion.CASCADE, to='product.producttypestatus'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.ForeignKey(db_column='id_status', on_delete=django.db.models.deletion.CASCADE, related_name='status_set', to='product.producttypestatus'),
        ),
    ]
