# Generated by Django 5.0.7 on 2024-07-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='interest_for_delay_type',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
