# Generated by Django 5.0.7 on 2024-08-04 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0002_initial'),
        ('product', '0003_product_interest_for_delay_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTranche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('condition', models.TextField(blank=True, null=True, verbose_name='condition')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='value')),
                ('lender', models.ForeignKey(db_column='id_lender', on_delete=django.db.models.deletion.CASCADE, related_name='tranche_lender', to='hierarchy.hierarchy')),
                ('product', models.ForeignKey(db_column='id_product', on_delete=django.db.models.deletion.CASCADE, related_name='tranche', to='product.product')),
            ],
            options={
                'db_table': 'product_tranche',
            },
        ),
    ]
