# Generated by Django 5.0.7 on 2024-08-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_producttranche'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttranche',
            name='sq',
            field=models.SmallIntegerField(default=1, verbose_name='sq'),
            preserve_default=False,
        ),
    ]
