# Generated by Django 5.0.7 on 2024-08-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_producttranche_sq'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttranche',
            name='launch_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
