# Generated by Django 5.0.7 on 2024-09-21 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_producttranche_launch_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productschedule',
            name='instalment_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producttranche',
            name='product',
            field=models.ForeignKey(db_column='id_product', on_delete=django.db.models.deletion.CASCADE, related_name='tranches', to='product.product'),
        ),
    ]
