# Generated by Django 5.0.7 on 2024-11-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_productschedule_instalment_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcalculation',
            name='interest_for_delay_calculation_base',
        ),
        migrations.RemoveField(
            model_name='productcalculation',
            name='interest_for_delay_rate',
        ),
        migrations.RemoveField(
            model_name='productcalculation',
            name='interest_for_delay_required',
        ),
        migrations.RemoveField(
            model_name='productcalculation',
            name='interest_for_delay_required_daily',
        ),
        migrations.RemoveField(
            model_name='productcalculation',
            name='interest_for_delay_total',
        ),
        migrations.AddField(
            model_name='productcalculation',
            name='is_interest_for_delay',
            field=models.BooleanField(default=False, verbose_name='product.calculation.is_interest_for_delay'),
        ),
    ]
