# Generated by Django 5.1.3 on 2024-12-29 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_productcalculation_interest_for_delay_calculation_base_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcalculation',
            name='instalment_accounting_interest_for_delay',
        ),
    ]
