# Generated by Django 5.1.3 on 2024-12-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_productcalculation_instalment_accounting_interest_for_delay'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcalculation',
            name='instalment_accounting',
            field=models.JSONField(null=True),
        ),
    ]
