# Generated by Django 5.1.3 on 2024-12-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_productcalculation_instalment_accounting'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcalculation',
            name='cost_list',
            field=models.JSONField(default=dict, verbose_name='product.calculation.cost_list'),
        ),
    ]
