# Generated by Django 5.1.3 on 2024-12-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_productcalculation_cost_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcalculation',
            name='balance_with_overpaid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='product.calculation.balance_with_overpaid'),
        ),
        migrations.AlterField(
            model_name='productcalculation',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='product.calculation.balance'),
        ),
    ]
