# Generated by Django 5.1.3 on 2025-01-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_productcalculation_balance_no_overpaid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcalculation',
            name='cost',
        ),
        migrations.AlterField(
            model_name='productcalculation',
            name='balance_with_overpaid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='product.calculation.balance_no_overpaid'),
        ),
    ]
