# Generated by Django 5.1.3 on 2025-01-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_remove_productcalculation_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcalculation',
            name='cost',
            field=models.JSONField(default=dict, verbose_name='product.calculation.cost_list'),
        ),
    ]
