# Generated by Django 5.1.3 on 2025-01-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_productcalculation_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcalculation',
            name='cost_list',
        ),
        migrations.AddField(
            model_name='productcalculation',
            name='cost_sum_per_day',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='product.calculation.cost_sum_per_day'),
        ),
        migrations.AlterField(
            model_name='productcalculation',
            name='cost',
            field=models.JSONField(default=dict, verbose_name='product.calculation.cost'),
        ),
        migrations.AddField(
            model_name='productcalculation',
            name='cost_occurrence',
            field=models.JSONField(default=dict, verbose_name='product.calculation.cost_occurence'),
        ),
    ]
