# Generated by Django 5.1.3 on 2025-03-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_remove_productcalculation_cost_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcalculation',
            name='interest_type',
            field=models.CharField(default='NOMINAL', max_length=50, verbose_name='product.calculation.interest_type'),
        ),
    ]
