# Generated by Django 5.1.3 on 2025-03-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_productcalculation_interest_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcalculation',
            name='interest_for_dela_max_cumulated_per_day',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='product.calculation.interest_for_dela_max_cumulated_per_day'),
        ),
        migrations.AddField(
            model_name='productcalculation',
            name='interest_for_delay_cumulated_per_day',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='product.calculation.interest_for_delay_cumulated_per_day'),
        ),
        migrations.AddField(
            model_name='productcalculation',
            name='interest_nominal_cumulated_per_day',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='product.calculation.interest_cumulated_per_day'),
        ),
    ]
