# Generated by Django 5.1.3 on 2025-04-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_remove_productcalculation_interest_for_dela_max_cumulated_per_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttranche',
            name='sq',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='sq'),
        ),
    ]
