# Generated by Django 5.2.5 on 2025-08-25 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0006_alter_hierarchy_email'),
        ('product', '0019_alter_producttranche_sq'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTypeStatusHierarchyM2M',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hierarchy', models.ForeignKey(db_column='id_hierarchy', on_delete=django.db.models.deletion.PROTECT, to='hierarchy.hierarchy')),
                ('product', models.ForeignKey(db_column='id_product', on_delete=django.db.models.deletion.CASCADE, to='product.producttypestatus')),
            ],
            options={
                'db_table': 'product_type_status_hierarchy_m2m',
            },
        ),
        migrations.AddField(
            model_name='producttypestatus',
            name='hierarchy',
            field=models.ManyToManyField(related_name='product_hierarchy_set', through='product.ProductTypeStatusHierarchyM2M', to='hierarchy.hierarchy'),
        ),
    ]
