# Generated by Django 5.2.5 on 2025-08-25 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0006_alter_hierarchy_email'),
        ('product', '0020_producttypestatushierarchym2m_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttypestatus',
            name='hierarchy',
            field=models.ManyToManyField(related_name='hierarchy_set', through='product.ProductTypeStatusHierarchyM2M', to='hierarchy.hierarchy'),
        ),
        migrations.AlterField(
            model_name='producttypestatushierarchym2m',
            name='product',
            field=models.ForeignKey(db_column='id_status', on_delete=django.db.models.deletion.CASCADE, to='product.producttypestatus'),
        ),
    ]
