# Generated by Django 5.2.7 on 2025-10-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_alter_producttypestatus_hierarchy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcalculation',
            name='early_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='product.calculation.early_payment'),
        ),
        migrations.AddField(
            model_name='productcalculation',
            name='early_payment_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='product.calculation.early_payment_total'),
        ),
    ]
