# Generated by Django 5.2.7 on 2025-10-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_productcalculation_early_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcalculation',
            name='capital_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='product.calculation.capital_payment'),
        ),
        migrations.AddField(
            model_name='productcalculation',
            name='capital_payment_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='product.calculation.capital_payment_total'),
        ),
    ]
