# Generated by Django 5.2.7 on 2025-10-21 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_productcalculation_capital_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttypeprocessflow',
            name='is_note_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='producttypeprocessflow',
            name='available_status',
            field=models.ForeignKey(blank=True, db_column='id_available_status', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_available_status', to='product.producttypestatus'),
        ),
        migrations.AlterField(
            model_name='producttypeprocessflow',
            name='status',
            field=models.ForeignKey(db_column='id_current_status', on_delete=django.db.models.deletion.CASCADE, related_name='product_status', to='product.producttypestatus'),
        ),
    ]
