# Generated by Django 5.2.7 on 2025-10-21 17:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_producttypeprocessflow_is_note_required_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttypeprocessflow',
            old_name='status',
            new_name='current_status',
        ),
        migrations.CreateModel(
            name='ProductStatusCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(db_column='id_product', on_delete=django.db.models.deletion.CASCADE, related_name='product_status_course', to='product.product')),
                ('status', models.ForeignKey(db_column='id_status', on_delete=django.db.models.deletion.CASCADE, to='product.producttypestatus')),
            ],
            options={
                'db_table': 'product_status_course',
            },
        ),
    ]
