# Generated by Django 5.0.7 on 2024-07-27 12:46

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adviser', '0001_initial'),
        ('broker', '0001_initial'),
        ('config', '0001_initial'),
        ('document', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='client.function.name')),
                ('sq', models.IntegerField()),
            ],
            options={
                'db_table': 'client_function',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='client', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='client.user')),
                ('status', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out'), ('PROSPECT', 'Prospect'), ('INVEST', 'Inwestycje / Pożyczka')], default='IN', max_length=10, verbose_name='client.status')),
                ('source', models.CharField(blank=True, choices=[('', '----'), ('WL', 'Własne'), ('POL', 'Polecenie'), ('CC', 'CC'), ('BRK', 'Pośrednik'), ('WK', 'Walk in')], max_length=200, null=True, verbose_name='client.source')),
                ('adviser', models.ForeignKey(blank=True, db_column='id_adviser', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_adviser', to='adviser.adviser', verbose_name='client.adviser')),
                ('broker', models.ForeignKey(blank=True, db_column='id_broker', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_broker', to='broker.broker', verbose_name='client.broker')),
                ('company', models.ForeignKey(blank=True, db_column='id_company', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='config.holdingcompany', verbose_name='client.company')),
                ('document_type', models.ForeignKey(db_column='id_document_type', on_delete=django.db.models.deletion.CASCADE, to='document.documenttype')),
            ],
            options={
                'db_table': 'user_client',
                'permissions': (('add:all', 'permissions.app.user.client.add.all'), ('add:department', 'permissions.app.user.client.add.department'), ('add:own', 'permissions.app.user.client.add.own'), ('list:all', 'permissions.app.user.client.list.all'), ('list:department', 'permissions.app.user.client.list.department'), ('list:own', 'permissions.app.user.client.list.own'), ('change:all', 'permissions.app.user.client.change.all'), ('change:department', 'permissions.app.user.client.change.department'), ('change:own', 'permissions.app.user.client.change.own')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ClientAccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500, verbose_name='client_access_token.token')),
                ('valid', models.BooleanField(default=True, verbose_name='client_access_token.valid')),
                ('client', models.ForeignKey(db_column='id_client', on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
            options={
                'db_table': 'client_access_token',
            },
        ),
        migrations.CreateModel(
            name='HistoricalProcessingAgreement',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='processing_agreement.name')),
                ('code', models.CharField(max_length=30, verbose_name='processing_agreement.code')),
                ('type', models.CharField(max_length=3, verbose_name='processing_agreement.type')),
                ('text', models.TextField(verbose_name='processing_agreement.text')),
                ('active', models.BooleanField(default=True, verbose_name='processing_agreement.active')),
                ('required', models.BooleanField(default=False, verbose_name='processing_agreement.required')),
                ('creation_date', models.DateTimeField(blank=True, editable=False)),
                ('confirmation_date', models.DateTimeField()),
                ('sq', models.IntegerField(default=0, verbose_name='processing_agreement.sq')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('confirmed_by', models.ForeignKey(blank=True, db_column='id_confirmed_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical processing agreement',
                'verbose_name_plural': 'historical processing agreements',
                'db_table': 'h_processing_agreement',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ProcessingAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='processing_agreement.name')),
                ('code', models.CharField(max_length=30, verbose_name='processing_agreement.code')),
                ('type', models.CharField(max_length=3, verbose_name='processing_agreement.type')),
                ('text', models.TextField(verbose_name='processing_agreement.text')),
                ('active', models.BooleanField(default=True, verbose_name='processing_agreement.active')),
                ('required', models.BooleanField(default=False, verbose_name='processing_agreement.required')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('confirmation_date', models.DateTimeField()),
                ('sq', models.IntegerField(default=0, verbose_name='processing_agreement.sq')),
                ('confirmed_by', models.ForeignKey(db_column='id_confirmed_by', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'processing_agreement',
            },
        ),
        migrations.CreateModel(
            name='HistoricalClientProcessingAgreement',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('text', models.TextField()),
                ('source', models.CharField(max_length=10)),
                ('value', models.BooleanField()),
                ('creation_date', models.DateTimeField(blank=True, editable=False)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, db_column='id_client', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='client.client')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('processing_agreement', models.ForeignKey(blank=True, db_column='id_processing_agreement', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='client.processingagreement')),
            ],
            options={
                'verbose_name': 'historical client processing agreement',
                'verbose_name_plural': 'historical client processing agreements',
                'db_table': 'h_client_processing_agreement',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ClientProcessingAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('source', models.CharField(max_length=10)),
                ('value', models.BooleanField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(db_column='id_client', on_delete=django.db.models.deletion.CASCADE, related_name='processing_agreement_set', to='client.client')),
                ('processing_agreement', models.ForeignKey(db_column='id_processing_agreement', on_delete=django.db.models.deletion.CASCADE, to='client.processingagreement')),
            ],
            options={
                'db_table': 'client_processing_agreement',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='processing_agreement',
            field=models.ManyToManyField(through='client.ClientProcessingAgreement', to='client.processingagreement'),
        ),
    ]
