# Generated by Django 5.0.7 on 2024-07-27 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adviser', '0001_initial'),
        ('document', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('user', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='broker_set', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('multi', models.BooleanField(default=False)),
                ('adviser', models.ForeignKey(db_column='id_adviser', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='broker_set', to='adviser.adviser', verbose_name='broker.adviser')),
                ('document_type', models.ForeignKey(db_column='id_document_type', on_delete=django.db.models.deletion.CASCADE, to='document.documenttype')),
            ],
            options={
                'db_table': 'user_broker',
                'permissions': (('view:all', 'permissions.app.broker.view.all'), ('view:own', 'permissions.app.broker.view.own'), ('list:all', 'permissions.app.broker.list.all'), ('list:own', 'permissions.app.broker.list.own')),
            },
        ),
    ]
