# Generated by Django 5.0.7 on 2024-07-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('type', models.CharField(default='file', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('file_path', models.CharField(max_length=300)),
                ('file_name', models.CharField(max_length=300)),
                ('file_original_name', models.CharField(max_length=300)),
                ('file_ext', models.CharField(max_length=10)),
                ('file_mime_type', models.CharField(max_length=200)),
                ('file_size', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('created_by_username', models.CharField(max_length=300)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'attachment',
            },
        ),
    ]
