# Generated by Django 5.0.7 on 2024-07-27 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=200)),
                ('label', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('active', models.BooleanField(default=True)),
                ('editable', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'dictionary',
            },
        ),
        migrations.CreateModel(
            name='DictionaryReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(db_column='table_name', max_length=100)),
                ('column_name', models.CharField(db_column='column_name', max_length=100)),
                ('dictionary', models.ForeignKey(db_column='id_dictionary', on_delete=django.db.models.deletion.CASCADE, to='dict.dictionary')),
            ],
            options={
                'db_table': 'dictionary_reference',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='DictionaryEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(db_column='label', max_length=200)),
                ('value', models.CharField(blank=True, db_column='value', max_length=20, null=True)),
                ('active', models.BooleanField(db_column='active', default=True)),
                ('sq', models.IntegerField(db_column='sq')),
                ('dictionary', models.ForeignKey(db_column='id_dictionary', on_delete=django.db.models.deletion.CASCADE, to='dict.dictionary')),
            ],
            options={
                'db_table': 'dictionary_entry',
                'permissions': (),
                'default_permissions': ('add', 'change'),
                'unique_together': {('dictionary', 'value')},
            },
        ),
    ]
