# Generated by Django 5.0.7 on 2024-07-27 12:46

import application.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HierarchyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'hierarchy_group',
            },
        ),
        migrations.CreateModel(
            name='HierarchyPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('sq', models.IntegerField()),
            ],
            options={
                'db_table': 'hierarchy_position',
            },
        ),
        migrations.CreateModel(
            name='Hierarchy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, null=True)),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('footer_disclaimer', models.TextField(blank=True, null=True)),
                ('type', models.CharField(default='DEP', max_length=10)),
                ('representative', models.JSONField(default=dict)),
                ('is_client_role', models.BooleanField(default=False)),
                ('level', models.IntegerField()),
                ('bank_transaction_files_directory', models.CharField(default='', max_length=50)),
                ('bank_account', models.CharField(default='', max_length=34)),
                ('sq', models.IntegerField(default=0)),
                ('address', models.ForeignKey(blank=True, db_column='id_address', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address', to='address.address')),
            ],
            options={
                'db_table': 'hierarchy',
                'permissions': (('list_user', 'permissions.app.user.list_user'),),
                'default_permissions': ('add', 'change', 'delete'),
            },
            bases=(application.models.CompanyDataMixin,),
        ),
    ]
