# Generated by Django 5.1.3 on 2025-06-20 11:52

import py3ws.utils.validators
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hierarchy',
            name='krs',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[utils.validators.krs_validator], verbose_name='krs'),
        ),
        migrations.AddField(
            model_name='hierarchy',
            name='nip',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[utils.validators.nip_validator], verbose_name='nip'),
        ),
        migrations.AddField(
            model_name='hierarchy',
            name='regon',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[py3ws.utils.validators.regon_validator], verbose_name='regon'),
        ),
    ]
