# Generated by Django 5.1.3 on 2025-06-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hierarchy',
            name='share_capital_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
