# Generated by Django 5.2.5 on 2025-08-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0004_alter_hierarchy_description_alter_hierarchy_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hierarchy',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
