# Generated by Django 5.2.5 on 2025-08-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0004_hierarchy_share_capital_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hierarchy',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hierarchy',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
