# Generated by Django 5.0.7 on 2024-07-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=300)),
                ('records', models.IntegerField(default=-1)),
                ('load_date', models.DateTimeField(auto_now_add=True)),
                ('subsidiary_company_code', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'fa_file',
                'unique_together': {('name', 'subsidiary_company_code')},
            },
        ),
    ]
