BBBB BBBBBB

XXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    

    BBBBB BBBBBBBBBBBBBBBB

    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX

    XXXXXXX
        XXXXXXXXXXX X
         XXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXX
         XXXXXXXXXXXXXXXXXX XXXXXXXXXX
            XXXXXXXXXXXXXXXX XXXXXX
        X
    XXXXXXXX

XXXXXXX

XXXXX XXXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX

    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXX
        BBBBB BBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXX
        BBBBB BBBBBBBBBBBBBBB
    XXXXXX

    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX

    BBBBB BBBBBBBBBBBBBBB

    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        BBBBB BBBBBBBBBBBBBBBBBBB
    XXXXXXXXX
    BBBBB BBBBBBBBBBBBBBBBBBBBBB

XXXXXX
XXXXXXX
XXXXXXX