# Generated by Django 5.0.7 on 2024-07-27 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRetailClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='product.retail.client.quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='product.retail.client.unit_price')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='product.retail.client.total_cost')),
                ('payment_type', models.CharField(blank=True, max_length=50, verbose_name='product.retail.client.payment_type')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='product.retail.client.total_cost')),
            ],
            options={
                'db_table': 'product_retail_client',
            },
        ),
        migrations.CreateModel(
            name='ProductRetailCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='product.retail.category.name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='product.retail.category.description')),
                ('sq', models.IntegerField()),
                ('parent', models.ForeignKey(blank=True, db_column='id_parent', null=True, on_delete=django.db.models.deletion.CASCADE, to='product_retail.productretailcategory')),
            ],
            options={
                'db_table': 'product_retail_category',
            },
        ),
        migrations.CreateModel(
            name='ProductRetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='product.retail.name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='product.retail.description')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='product.retail.unit_price')),
                ('category', models.ForeignKey(db_column='id_category', on_delete=django.db.models.deletion.CASCADE, to='product_retail.productretailcategory')),
            ],
            options={
                'db_table': 'product_retail',
            },
        ),
    ]
