# Generated by Django 5.0.7 on 2024-07-27 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adviser',
            fields=[
                ('user', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='adviser_set', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('document_type', models.ForeignKey(db_column='id_document_type', on_delete=django.db.models.deletion.CASCADE, to='document.documenttype')),
            ],
            options={
                'db_table': 'user_adviser',
            },
        ),
    ]
