# Generated by Django 5.0.7 on 2024-07-27 12:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attachment', '0001_initial'),
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=300, verbose_name='invoice.number')),
                ('issuer', models.CharField(max_length=500, verbose_name='invoice.issuer')),
                ('recipient', models.CharField(max_length=500, verbose_name='invoice.recipient')),
                ('file_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='invoice.file_name')),
                ('type', models.CharField(max_length=20, verbose_name='invoice.type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='invoice.description')),
                ('document', models.OneToOneField(db_column='id_document', on_delete=django.db.models.deletion.CASCADE, to='document.document')),
            ],
            options={
                'db_table': 'fa_invoice',
                'default_permissions': ('add', 'change'),
            },
        ),
        migrations.CreateModel(
            name='InvoiceAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.ForeignKey(db_column='id_attachment', on_delete=django.db.models.deletion.CASCADE, to='attachment.attachment')),
                ('invoice', models.ForeignKey(db_column='id_invoice', on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice')),
            ],
            options={
                'db_table': 'fa_invoice_attachment',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='attachments',
            field=models.ManyToManyField(through='invoice.InvoiceAttachment', to='attachment.attachment'),
        ),
        migrations.CreateModel(
            name='InvoiceExtraItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='invoice.extra.item.name')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='invoice.extra.item.value')),
                ('invoice', models.ForeignKey(blank=True, db_column='id_invoice', on_delete=django.db.models.deletion.CASCADE, related_name='extra_item_set', to='invoice.invoice')),
            ],
            options={
                'db_table': 'fa_invoice_extra_item',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='invoice.item.name')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='invoice.item.code')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='invoice.item.quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='invoice.item.unit_price')),
                ('unit_of_measure', models.CharField(max_length=50, verbose_name='invoice.item.unit_of_measure')),
                ('tax_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='invoice.item.tax_value')),
                ('invoice', models.ForeignKey(blank=True, db_column='id_invoice', on_delete=django.db.models.deletion.CASCADE, related_name='item_set', to='invoice.invoice')),
            ],
            options={
                'db_table': 'fa_invoice_item',
            },
        ),
    ]
